//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExapisSOP.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExapisSOP.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   DefaultHostRunner_Exception に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DefaultHostRunner_Exception {
            get {
                return ResourceManager.GetString("DefaultHostRunner_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EventLoopContext_InvalidOperationException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EventLoopContext_InvalidOperationException {
            get {
                return ResourceManager.GetString("EventLoopContext_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HostRunner_Create_ArgumentException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HostRunner_Create_ArgumentException {
            get {
                return ResourceManager.GetString("HostRunner_Create_ArgumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   HostRunner_Create_InvalidOperationException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string HostRunner_Create_InvalidOperationException {
            get {
                return ResourceManager.GetString("HostRunner_Create_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InitFinalContext_InvalidOperationException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InitFinalContext_InvalidOperationException {
            get {
                return ResourceManager.GetString("InitFinalContext_InvalidOperationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   InvalidPathFormatException {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string InvalidPathFormatException {
            get {
                return ResourceManager.GetString("InvalidPathFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PathString_PlatformNotSupportedException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PathString_PlatformNotSupportedException {
            get {
                return ResourceManager.GetString("PathString_PlatformNotSupportedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TerminationException に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TerminationException {
            get {
                return ResourceManager.GetString("TerminationException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TerminationException_withInnerError に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TerminationException_withInnerError {
            get {
                return ResourceManager.GetString("TerminationException_withInnerError", resourceCulture);
            }
        }
    }
}
